server:
  port: 50001
spring:
  application:
    name: user-consumer
#  profiles:
#    include: jdbc,redis,dubbo
#  cloud:
#    consul:
#      host: localhost
#      port: 8500
#      discovery:
#        health-check-path: /actuator/health
#        service-name: user-provider
#        enabled: true
#      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:50001/eureka/,http://localhost:50002/eureka/,http://localhost:50003/eureka/

feign:
  hystrix:
    enabled: true
