#eureka:
#  client:
#    service-url:
#      defaultZone: http://eureka1:50001/eureka/,http://eureka2:50002/eureka/
server:
  port: 10000
spring:
  application:
    name: cloud-zipkin
  zipkin:
    base-url: http://localhost:10000/
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:50001/eureka/,http://eureka2:50002/eureka/
management:
  metrics:
    web:
      server:
        auto-time-requests: false
