#HA 版: 通过运行多个实例并请求他们相互注册, 通过defaultZone 注定本实例要注册到哪些其他的节点
---
spring:
  profiles: Peer1
  application:
    name: eureka-server
server:
  port: 50001
eureka:
  instance:
      hostname: eureka1
  client:
    service-url:
      defaultZone: http://eureka2:50002/eureka/
#      defaultZone: http://eureka2:50002/eureka/,http://eureka3:50003/eureka/

---
spring:
  profiles: Peer2
  application:
    name: eureka-server
server:
   port: 50002
eureka:
  instance:
      hostname: eureka2
  client:
    serviceUrl:
       defaultZone: http://eureka1:50001/eureka/
#       defaultZone: http://eureka1:50001/eureka/,http://eureka3:50003/eureka/

---
spring:
  profiles: Peer3
  application:
    name: eureka-server
server:
  port: 50003
eureka:
  instance:
      hostname: eureka3
  client:
    serviceUrl:
      defaultZone: http://eureka1:50001/eureka/,http://eureka2:50002/eureka/
