#HA 版: 通过运行多个实例并请求他们相互注册, 通过defaultZone 注定本实例要注册到哪些其他的节点
---
spring:
  profiles: eureka1
  application:
    name: eureka-server
server:
  port: 50001
eureka:
  instance:
    hostname: eureka1
  client:
    service-url:
      defaultZone: http://eureka2:50002/eureka/,http://eureka3:50003/eureka/

---
spring:
  profiles: eureka2
  application:
    name: eureka-server
server:
   port: 50002
eureka:
  instance:
    hostname: eureka2
  client:
    serviceUrl:
       defaultZone: http://eureka1:50001/eureka/,http://eureka3:50003/eureka/

---
spring:
  profiles: eureka3
  application:
    name: eureka-server
server:
  port: 50003
eureka:
  instance:
    hostname: eureka3
  client:
    serviceUrl:
      defaultZone: http://eureka1:50001/eureka/,http://eureka2:50002/eureka/


#---
#spring:
#  profiles: eureka1 # 指定profile=peer1
#  application:
#    name: Eureka-Server
#server:
#  port: 50001   # 注册服务的端口号
#eureka:
#  instance:
#    hostname: eureka1   # 指定当profile=peer1时，主机名
#  client:
#    serviceUrl:
#      defaultZone: http://eureka2:50002/eureka/  # 将自己注册到peer2这个Eureka上面去
#
#---
#spring:
#  profiles: eureka2
#  application:
#    name: Eureka-Server
#server:
#  port: 50002
#eureka:
#  instance:
#    hostname: eureka2
#  client:
#    serviceUrl:
#      defaultZone: http://eureka1:50001/eureka/  # 服务注册地址，将自己注册到peer2上去