server:
  port: 8999
spring:
  application:
    name: api-docs
zuul:
  routes:
    user-provider:
      path: /user-provider/**
    user-consumer:
      path: /user-consumer/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:50001/eureka/,http://eureka2:50002/eureka/
  instance:
    hostname:

swagger:
  resources-provider:
    swagger-resources:
      - name: 用户消费者模块
        url: /user-consumer/v2/api-docs
      - name: 用户提供者模块
        url: /user-provider/v2/api-docs
  enabled: true
